### ISSUE TITLE
Create API Specific Commands from PostgREST

### ISSUE THREAD

**Issue by cboecking** [danielgtaylor/restish#235]
Hi Daniel, thank you for all that you have done with this project! 

I am having difficulty creating API specific commands (https://rest.sh/#/guide?id=api-specific-commands) from a https://PostgREST.org endpoint. I believe I know why; however, I just wanted to confirm my details and get your advice:

- I want to be able to use rest.sh with postgREST (which I love!!)
- I am getting an error (see below(
- I believe the error is because postgREST publishes a "swagger":"2.0"  openapi description (which you clearly do not support)
- Here is an example endpoint I created to help communicate with you: 
  - http://3.92.228.30:3000/  (openapi descriptor)
  - http://3.92.228.30:3000/todo (specific record from specific source)

I will be going to the postgREST team to help support them to update the tool to work with rest.sh. Please offer any thoughts and advice as you deem appropriate. 

**Here is the error:**
rest-sh-01 /usr/local/bin🔒
❯ ./restish api configure jelly http://3.92.228.30:3000/
Setting up a `default` profile
? Select option for profile `default` Finished with profile
? Select option Save and exit

rest-sh-01 /usr/local/bin🔒 took 8s
❯ ./restish jelly --help
panic: could not detect API type: http://3.92.228.30:3000/

goroutine 1 [running]:
github.com/danielgtaylor/restish/cli.Run()
	/home/runner/work/restish/restish/cli/cli.go:822 +0xb76
main.main()
	/home/runner/work/restish/restish/main.go:40 +0x23a

**Thank you for your time and consideration! Chuck Boecking**

**Comment by danielgtaylor** [comment]
Thanks for the clear write-up, and for the kind words.

For v2, Restish core is going to stay focused on OpenAPI 3.x rather than adding Swagger/OpenAPI 2.0 support. Swagger 2.0 is old enough now that the maintenance cost and edge-case surface do not feel worth carrying in core.

A future plugin could support Swagger/OpenAPI 2.0 by translating or generating commands outside the core command-generation path, and we'd be open to improving plugin protocol pieces if that became useful. But for Restish core, I'm going to close this as not planned.
