### ISSUE TITLE
Multiple APIs with same base URL prevents any interaction with `api` subcommand

### ISSUE THREAD

**Issue by logicbomb421** [danielgtaylor/restish#262]
I accidentally created an API with the same base URL as another via the interactive `restish api configure` and afterwards I cannot interact with `restish api` in any way due to the following panic:

```
panic: multiple APIs configured with the same base URL: <BASE URL VALUE>

goroutine 1 [running]:
github.com/danielgtaylor/restish/cli.initAPIConfig.func6(0x1400083fbf0?, 0x1400083fb90, 0x1400007c3c0)
	/home/runner/work/restish/restish/cli/apiconfig.go:245 +0x204
github.com/danielgtaylor/restish/cli.initAPIConfig()
	/home/runner/work/restish/restish/cli/apiconfig.go:261 +0x960
github.com/danielgtaylor/restish/cli.Init({0x103094b9b, 0x7}, {0x10334a270, 0x6})
	/home/runner/work/restish/restish/cli/cli.go:571 +0x1f68
main.main()
	/home/runner/work/restish/restish/main.go:25 +0x1b8
```

I was able to fix this by manually editing the JSON file after digging it up, however it would be helpful if at least the `api edit` command could open an invalid config to make fixing this easier. Alternatively, `api configure` could check to see if the base URL entered is a duplicate and refuse to write.

Please let me know if more info is needed.

Thanks!

---
restish version 0.20.0

**Comment by jakelauer** [comment]
Note - having multiple APIs with the same base URL is a real use-case; in my case, multiple environments can be reached using the same hostname and path, but with a different query string value (`env=`). I would use the `profiles` option to manage this, except each environment has its own OpenAPI spec, so I am forced to create separate individual API configurations for each.

**Comment by danielgtaylor** [comment]
Thanks for reporting this. I checked this against v2.0.0, and duplicate base URLs no longer prevent the `api` subcommands from working.

I verified locally with a config containing two APIs that share the same base URL:

```json
{
  "apis": {
    "one": {"base_url": "https://api.example.com"},
    "two": {"base_url": "https://api.example.com"}
  }
}
```

With that config, v2 can still list and inspect APIs:

```bash
restish api list
restish api inspect one
```

`api list` shows both entries rather than panicking:

```text
one  https://api.example.com  0 operations  0 profiles
two  https://api.example.com  0 operations  0 profiles
```

For direct URL requests where multiple APIs match equally, v2 reports an ambiguity and asks you to use the API short-name form instead, so `restish one/...` or `restish two/...` remains explicit.

I'm closing this as fixed in v2. Please give Restish v2.0.0 a try.
